### ISSUE TITLE
no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by shankardevy** [benignware/schedulable#8]
I am getting error on the line `  acts_as_schedulable :schedule`  as 'no implicit conversion of Symbol into Integer'

```             
class Event < ActiveRecord::Base
  acts_as_schedulable :schedule

end
```

**Comment by rexblack** [comment]
This is probably related to the following issue: The main release branch of ice_cube-library does only support english messages and throws an exception if the current locale is not supported for generating the schedule string. This is now handled by schedulable by providing the english message as return value of the to_s-method of the schedule. Fixed by 4413683 on master and will be contained in upcoming maintainance release.
If you need other languages, please checkout the international branch of ice_cube as described in the Internationalization section of schedulable's README.md:
```ruby
gem 'ice_cube', git: 'git://github.com/joelmeyerhamme/ice_cube.git', branch: 'international' 
```
